var = {
    'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    'wsgi.input': '<_io.BufferedReader name=6>',
    'CONTENT_TYPE': 'multipart/form-data; boundary=---------------------------1816558597375848913106741407',
    'GDMSESSION': 'ubuntu',
    'SERVER_PORT': '8000',
    'CSRF_COOKIE': 'NkCcAYsAtn3iOoSBfb027NVcK4tTOsfC',
    'DESKTOP_AUTOSTART_ID': '10e5414b9691906c71142913324267671600000027350003',
    'ORACLE_HOME': '/usr/lib/oracle/11.2/client64',
    'QUERY_STRING': '',
    'DESKTOP_SESSION': 'ubuntu',
    'XDG_CURRENT_DESKTOP': 'Unity',
    'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/',
    'LC_IDENTIFICATION': 'ko_KR.UTF-8',
    'LC_PAPER': 'ko_KR.UTF-8',
    'LOGNAME': 'hong',
    'PYTHONUNBUFFERED': '1',
    'wsgi.multithread': True,
    'SSH_AGENT_PID': '2772',
    'GIO_LAUNCHED_DESKTOP_FILE_PID': '4825',
    'QT_IM_MODULE': 'fcitx',
    'GNOME_KEYRING_CONTROL': '/tmp/keyring-0GBPYj',
    'PWD': '/home/hong',
    'PATH_INFO': '/file/upload',
    'XDG_CONFIG_DIRS': '/etc/xdg/xdg-ubuntu:/etc/xdg',
    'wsgi.run_once': False,
    'PYTHONIOENCODING': 'UTF-8',
    'SHELL': '/bin/bash',
    'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated',
    'LD_LIBRARY_PATH': '/home/hong/dev/tool/pycharm-4.0.6/bin:',
    'USER': 'hong',
    'wsgi.file_wrapper': "<class 'wsgiref.util.FileWrapper'>",
    'DJANGO_SETTINGS_MODULE': 'py_board.settings',
    'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0',
    'XAUTHORITY': '/home/hong/.Xauthority',
    'LC_TELEPHONE': 'ko_KR.UTF-8',
    'TNS_ADMIN': '/usr/lib/oracle/11.2/client64',
    'wsgi.multiprocess': False,
    'GTK_IM_MODULE': 'fcitx',
    'wsgi.version': (1, 0),
    'LC_MEASUREMENT': 'ko_KR.UTF-8',
    'XFILESEARCHPATH': '/usr/dt/app-defaults/%L/Dt',
    'MANDATORY_PATH': '/usr/share/gconf/ubuntu.mandatory.path',
    'HTTP_REFERER': 'http://localhost:8000/board/freeboard/add',
    'HTTP_ACCEPT_LANGUAGE': 'ko-KR,ko;q=0.8,en-US;q=0.5,en;q=0.3',
    'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-ovkMUahZXB,guid=b2aed5c849900d88116dbe7a0000001c',
    'LC_ADDRESS': 'ko_KR.UTF-8',
    'SERVER_SOFTWARE': 'WSGIServer/0.2',
    'GPG_AGENT_INFO': '/tmp/keyring-0GBPYj/gpg:0:1',
    'SERVER_PROTOCOL': 'HTTP/1.1',
    'SESSION_MANAGER': 'local/hong-pc:@/tmp/.ICE-unix/2735,unix/hong-pc:/tmp/.ICE-unix/2735',
    'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0',
    'LC_TIME': 'ko_KR.UTF-8', 'UBUNTU_MENUPROXY': 'libappmenu.so',
    'wsgi.url_scheme': 'http',
    'HTTP_HOST': 'localhost:8000',
    'REQUEST_METHOD': 'POST',
    'HTTP_CONNECTION': 'keep-alive',
    'LC_NAME': 'ko_KR.UTF-8',
    'XMODIFIERS': '@im=fcitx',
    'DISPLAY': ':0',
    'wsgi.errors': "<_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>",
    'NLSPATH': '/usr/dt/lib/nls/msg/%L/%N.cat',
    'LANG': 'ko_KR.UTF-8',
    'XDG_SESSION_COOKIE': 'c4bbfd6c9e7775f2d0782c9f00000005-1429133242.152718-688453290',
    'RUN_MAIN': 'true',
    'GATEWAY_INTERFACE': 'CGI/1.1',
    'GIO_LAUNCHED_DESKTOP_FILE': '/usr/share/applications/pycharm.desktop',
    'DEFAULTS_PATH': '/usr/share/gconf/ubuntu.default.path',
    'LC_MONETARY': 'ko_KR.UTF-8',
    'LANGUAGE': 'ko:en',
    'PYTHONPATH': '/home/hong/dev/pycharm/python3/django/py_board',
    'TZ': 'Asia/Seoul',
    'CLASSPATH': '/home/hong/dev/tool/pycharm-4.0.6/bin/../lib/bootstrap.jar:/home/hong/dev/tool/pycharm-4.0.6/bin/../lib/extensions.jar:/home/hong/dev/tool/pycharm-4.0.6/bin/../lib/util.jar:/home/hong/dev/tool/pycharm-4.0.6/bin/../lib/jdom.jar:/home/hong/dev/tool/pycharm-4.0.6/bin/../lib/log4j.jar:/home/hong/dev/tool/pycharm-4.0.6/bin/../lib/trove4j.jar:/home/hong/dev/tool/pycharm-4.0.6/bin/../lib/jna.jar',
    'SSH_AUTH_SOCK': '/tmp/keyring-0GBPYj/ssh',
    'REMOTE_HOST': '',
    'CONTENT_LENGTH': '34201',
    'SCRIPT_NAME': '',
    'GNOME_KEYRING_PID': '2724',
    'LC_NUMERIC': 'ko_KR.UTF-8',
    'HOME': '/home/hong',
    'REMOTE_ADDR': '127.0.0.1',
    'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
    'COMPIZ_CONFIG_PROFILE': 'ubuntu',
    'HTTP_COOKIE': 'csrftoken=NkCcAYsAtn3iOoSBfb027NVcK4tTOsfC; djdt=show; sessionid=hltqp7vgdh2lsi77fv5n2a7c1nn8q2z1; messages="64deae1cfcf71dcf7023aa35fec5e84858cd6f9a$[[\\"__json_message\\"\\0540\\05425\\054\\"Successfully signed in as hong.\\"]]"',
    'SERVER_NAME': 'localhost',
    'PATH': '/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/home/hong/.rvm/bin',
    'PYCHARM_HOSTED': '1',
    'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0'
}


s = '테스트.pdf'
print(s.encode('utf-8'))

import urllib.parse

a = urllib.parse.urlencode(query=s, encoding='utf-8')
print(a)